/*
 * File: app/store/ComboBox.js
 *
 * This file was generated by Sencha Architect version 4.1.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.2.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.2.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('ExtJs6ExamplesWorld.store.ComboBox', {
    extend: 'Ext.data.Store',

    requires: [
        'ExtJs6ExamplesWorld.model.ComboBox',
        'Ext.data.proxy.Ajax',
        'Ext.data.reader.Array'
    ],

    constructor: function(cfg) {
        var me = this;
        cfg = cfg || {};
        me.callParent([Ext.apply({
            storeId: 'ComboBox',
            model: 'ExtJs6ExamplesWorld.model.ComboBox',
            data: [
                {
                    abbr: 'rem',
                    state: 'eveniet',
                    description: 'vel',
                    country: 'consequatur'
                },
                {
                    abbr: 'voluptas',
                    state: 'sed',
                    description: 'cupiditate',
                    country: 'impedit'
                },
                {
                    abbr: 'ut',
                    state: 'qui',
                    description: 'dolorem',
                    country: 'assumenda'
                },
                {
                    abbr: 'aperiam',
                    state: 'molestiae',
                    description: 'rerum',
                    country: 'quis'
                },
                {
                    abbr: 'aut',
                    state: 'necessitatibus',
                    description: 'temporibus',
                    country: 'aut'
                },
                {
                    abbr: 'accusantium',
                    state: 'officiis',
                    description: 'quia',
                    country: 'autem'
                },
                {
                    abbr: 'temporibus',
                    state: 'fuga',
                    description: 'provident',
                    country: 'molestiae'
                },
                {
                    abbr: 'voluptate',
                    state: 'soluta',
                    description: 'maiores',
                    country: 'fugit'
                },
                {
                    abbr: 'atque',
                    state: 'sunt',
                    description: 'sit',
                    country: 'quis'
                },
                {
                    abbr: 'placeat',
                    state: 'quam',
                    description: 'dolores',
                    country: 'ea'
                },
                {
                    abbr: 'minima',
                    state: 'dolorum',
                    description: 'distinctio',
                    country: 'nam'
                },
                {
                    abbr: 'recusandae',
                    state: 'nihil',
                    description: 'illo',
                    country: 'inventore'
                },
                {
                    abbr: 'recusandae',
                    state: 'placeat',
                    description: 'consequatur',
                    country: 'ipsam'
                },
                {
                    abbr: 'in',
                    state: 'consequatur',
                    description: 'ipsam',
                    country: 'maxime'
                },
                {
                    abbr: 'provident',
                    state: 'vel',
                    description: 'illo',
                    country: 'perferendis'
                },
                {
                    abbr: 'libero',
                    state: 'deserunt',
                    description: 'porro',
                    country: 'fugit'
                },
                {
                    abbr: 'sit',
                    state: 'illo',
                    description: 'tenetur',
                    country: 'natus'
                },
                {
                    abbr: 'corrupti',
                    state: 'iusto',
                    description: 'consequuntur',
                    country: 'voluptatum'
                },
                {
                    abbr: 'voluptatem',
                    state: 'occaecati',
                    description: 'quas',
                    country: 'vitae'
                },
                {
                    abbr: 'architecto',
                    state: 'officia',
                    description: 'ad',
                    country: 'enim'
                },
                {
                    abbr: 'aut',
                    state: 'itaque',
                    description: 'natus',
                    country: 'labore'
                },
                {
                    abbr: 'culpa',
                    state: 'suscipit',
                    description: 'vel',
                    country: 'aut'
                },
                {
                    abbr: 'omnis',
                    state: 'molestiae',
                    description: 'ratione',
                    country: 'corrupti'
                },
                {
                    abbr: 'consequatur',
                    state: 'aut',
                    description: 'est',
                    country: 'aut'
                },
                {
                    abbr: 'neque',
                    state: 'dolor',
                    description: 'sunt',
                    country: 'esse'
                },
                {
                    abbr: 'aliquid',
                    state: 'error',
                    description: 'quia',
                    country: 'est'
                },
                {
                    abbr: 'quo',
                    state: 'dolor',
                    description: 'incidunt',
                    country: 'iusto'
                },
                {
                    abbr: 'quibusdam',
                    state: 'cum',
                    description: 'fugit',
                    country: 'voluptatem'
                },
                {
                    abbr: 'fugiat',
                    state: 'occaecati',
                    description: 'quia',
                    country: 'impedit'
                },
                {
                    abbr: 'temporibus',
                    state: 'exercitationem',
                    description: 'cum',
                    country: 'voluptatem'
                }
            ],
            proxy: {
                type: 'ajax',
                reader: {
                    type: 'array'
                }
            }
        }, cfg)]);
    }
});