/*
 * File: app/view/BasicButton.js
 *
 * This file was generated by Sencha Architect version 4.1.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.2.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.2.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('ExtJs6ExamplesWorld.view.BasicButton', {
    extend: 'Ext.container.Container',
    alias: 'widget.BasicButton',

    requires: [
        'ExtJs6ExamplesWorld.view.aboutViewModel3',
        'Ext.menu.Menu',
        'Ext.menu.Item',
        'Ext.button.Split',
        'Ext.button.Segmented'
    ],

    viewModel: {
        type: 'basicbutton'
    },
    id: 'BasicButton',
    itemId: 'BasicButton',

    layout: {
        type: 'vbox',
        align: 'center',
        pack: 'center'
    },
    items: [
        {
            xtype: 'button',
            margin: 2,
            text: 'NORMAL'
        },
        {
            xtype: 'button',
            disabled: true,
            margin: 2,
            text: 'Disabled'
        },
        {
            xtype: 'button',
            handler: function(button, e) {
                alert("Hello World");
            },
            margin: 2,
            text: 'Handler'
        },
        {
            xtype: 'button',
            id: 'Action',
            itemId: 'Action',
            text: 'Action'
        },
        {
            xtype: 'button',
            margin: 2,
            iconCls: 'button-home-medium',
            text: 'Icon'
        },
        {
            xtype: 'button',
            margin: 2,
            enableToggle: true,
            text: 'Toggle Buttons'
        },
        {
            xtype: 'button',
            text: 'Menu',
            menu: {
                xtype: 'menu',
                width: 120,
                items: [
                    {
                        xtype: 'menuitem',
                        text: 'Menu Item'
                    },
                    {
                        xtype: 'menuitem',
                        text: 'Menu Item'
                    },
                    {
                        xtype: 'menuitem',
                        text: 'Menu Item'
                    }
                ]
            }
        },
        {
            xtype: 'splitbutton',
            margin: 2,
            text: 'Split',
            menu: {
                xtype: 'menu',
                width: 120,
                items: [
                    {
                        xtype: 'menuitem',
                        text: 'Menu Item'
                    },
                    {
                        xtype: 'menuitem',
                        text: 'Menu Item'
                    },
                    {
                        xtype: 'menuitem',
                        text: 'Menu Item'
                    }
                ]
            }
        },
        {
            xtype: 'button',
            href: 'http://www.google.com/',
            text: 'Link'
        },
        {
            xtype: 'button',
            margin: 2,
            text: 'Link'
        },
        {
            xtype: 'segmentedbutton',
            items: [
                {
                    handler: function(button, e) {
                        alert("Hello World");
                    },
                    text: 'MyButton'
                },
                {
                    text: 'MyButton'
                },
                {
                    text: 'MyButton'
                }
            ]
        },
        {
            xtype: 'segmentedbutton',
            margin: 2,
            vertical: true,
            items: [
                {
                    handler: function(button, e) {
                        alert("Hello World");
                    },
                    text: 'MyButton'
                },
                {
                    text: 'MyButton'
                },
                {
                    text: 'MyButton'
                }
            ]
        }
    ]

});