/*
 * File: app/view/FileField.js
 *
 * This file was generated by Sencha Architect version 4.1.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.2.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.2.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('ExtJs6ExamplesWorld.view.FileField', {
    extend: 'Ext.container.Container',
    alias: 'widget.FileField',

    requires: [
        'ExtJs6ExamplesWorld.view.aboutViewModel7',
        'Ext.form.field.File'
    ],

    viewModel: {
        type: 'filefield'
    },
    id: 'FileField',
    itemId: 'FileField',

    layout: {
        type: 'vbox',
        align: 'center',
        pack: 'center'
    },
    items: [
        {
            xtype: 'filefield',
            width: 600,
            fieldLabel: 'filefield'
        }
    ]

});