/*
 * File: app/view/MyViewport.js
 *
 * This file was generated by Sencha Architect version 4.1.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.2.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.2.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('ExtJs6ExamplesWorld.view.MyViewport', {
    extend: 'Ext.container.Viewport',
    alias: 'widget.myviewport',

    requires: [
        'ExtJs6ExamplesWorld.view.MyViewportViewModel',
        'Ext.toolbar.Toolbar',
        'Ext.button.Button',
        'Ext.menu.Menu',
        'Ext.menu.Item'
    ],

    viewModel: {
        type: 'myviewport'
    },
    height: 250,
    padding: 10,
    width: 400,

    layout: {
        type: 'vbox',
        align: 'stretch',
        pack: 'center'
    },
    items: [
        {
            xtype: 'toolbar',
            dock: 'top',
            items: [
                {
                    xtype: 'button',
                    width: 150,
                    text: 'Main',
                    menu: {
                        xtype: 'menu',
                        width: 120,
                        items: [
                            {
                                xtype: 'menuitem',
                                handler: function(item, e) {
                                    var workspace = Ext.ComponentQuery.query('container[itemId=workspace]')[0];

                                    var readme = Ext.create('ExtJs6ExamplesWorld.view.ReadMe');

                                    //
                                    workspace.removeAll();
                                    workspace.add(readme);
                                },
                                text: 'ReadMe'
                            },
                            {
                                xtype: 'menuitem',
                                handler: function(item, e) {
                                    var workspace = Ext.ComponentQuery.query('container[itemId=workspace]')[0];

                                    var o = Ext.create('ExtJs6ExamplesWorld.view.Sample');

                                    //
                                    workspace.removeAll();
                                    workspace.add(o);
                                },
                                text: 'Sample'
                            },
                            {
                                xtype: 'menuitem',
                                handler: function(item, e) {
                                    var workspace = Ext.ComponentQuery.query('container[itemId=workspace]')[0];

                                    var setting = Ext.create('ExtJs6ExamplesWorld.view.Setting');

                                    //
                                    workspace.removeAll();
                                    workspace.add(setting);
                                },
                                text: 'Setting'
                            },
                            {
                                xtype: 'menuitem',
                                handler: function(item, e) {
                                    var workspace = Ext.ComponentQuery.query('container[itemId=workspace]')[0];

                                    //
                                    workspace.removeAll();
                                },
                                text: 'Remove'
                            },
                            {
                                xtype: 'menuitem',
                                handler: function(item, e) {
                                    var workspace = Ext.ComponentQuery.query('container[itemId=workspace]')[0];

                                    var about = Ext.create('ExtJs6ExamplesWorld.view.About');

                                    //
                                    workspace.removeAll();
                                    workspace.add(about);
                                },
                                text: 'About'
                            }
                        ]
                    }
                },
                {
                    xtype: 'button',
                    text: 'Components',
                    menu: {
                        xtype: 'menu',
                        width: 120,
                        items: [
                            {
                                xtype: 'menuitem',
                                handler: function(item, e) {
                                    var workspace = Ext.ComponentQuery.query('container[itemId=workspace]')[0];

                                    var o = Ext.create('ExtJs6ExamplesWorld.view.Button');

                                    //
                                    workspace.removeAll();
                                    workspace.add(o);
                                },
                                text: 'Button'
                            },
                            {
                                xtype: 'menuitem',
                                handler: function(item, e) {
                                    var workspace = Ext.ComponentQuery.query('container[itemId=workspace]')[0];

                                    var o = Ext.create('ExtJs6ExamplesWorld.view.NumberField');

                                    //
                                    workspace.removeAll();
                                    workspace.add(o);
                                },
                                text: 'Number Field'
                            },
                            {
                                xtype: 'menuitem',
                                handler: function(item, e) {
                                    var workspace = Ext.ComponentQuery.query('container[itemId=workspace]')[0];

                                    var o = Ext.create('ExtJs6ExamplesWorld.view.DateField');

                                    //
                                    workspace.removeAll();
                                    workspace.add(o);
                                },
                                text: 'Date Field'
                            },
                            {
                                xtype: 'menuitem',
                                handler: function(item, e) {
                                    var workspace = Ext.ComponentQuery.query('container[itemId=workspace]')[0];

                                    var o = Ext.create('ExtJs6ExamplesWorld.view.ComboBox');

                                    //
                                    workspace.removeAll();
                                    workspace.add(o);
                                },
                                text: 'ComboBox'
                            },
                            {
                                xtype: 'menuitem',
                                handler: function(item, e) {
                                    var workspace = Ext.ComponentQuery.query('container[itemId=workspace]')[0];

                                    var o = Ext.create('ExtJs6ExamplesWorld.view.FileField');

                                    //
                                    workspace.removeAll();
                                    workspace.add(o);
                                },
                                text: 'FileField'
                            },
                            {
                                xtype: 'menuitem',
                                handler: function(item, e) {
                                    var workspace = Ext.ComponentQuery.query('container[itemId=workspace]')[0];

                                    var o = Ext.create('ExtJs6ExamplesWorld.view.TextareaField');

                                    //
                                    workspace.removeAll();
                                    workspace.add(o);
                                },
                                text: 'TextareaField'
                            },
                            {
                                xtype: 'menuitem',
                                handler: function(item, e) {
                                    var workspace = Ext.ComponentQuery.query('container[itemId=workspace]')[0];

                                    var o = Ext.create('ExtJs6ExamplesWorld.view.Radio');

                                    //
                                    workspace.removeAll();
                                    workspace.add(o);
                                },
                                text: 'Radio'
                            },
                            {
                                xtype: 'menuitem',
                                handler: function(item, e) {
                                    var workspace = Ext.ComponentQuery.query('container[itemId=workspace]')[0];

                                    var o = Ext.create('ExtJs6ExamplesWorld.view.Slider');

                                    //
                                    workspace.removeAll();
                                    workspace.add(o);
                                },
                                text: 'Slider'
                            },
                            {
                                xtype: 'menuitem',
                                handler: function(item, e) {
                                    var workspace = Ext.ComponentQuery.query('container[itemId=workspace]')[0];

                                    var o = Ext.create('ExtJs6ExamplesWorld.view.DisplayField');

                                    //
                                    workspace.removeAll();
                                    workspace.add(o);
                                },
                                text: 'Display Field'
                            },
                            {
                                xtype: 'menuitem',
                                handler: function(item, e) {
                                    var workspace = Ext.ComponentQuery.query('container[itemId=workspace]')[0];

                                    var o = Ext.create('ExtJs6ExamplesWorld.view.HiddenField');

                                    //
                                    workspace.removeAll();
                                    workspace.add(o);
                                },
                                text: 'Hidden Field'
                            },
                            {
                                xtype: 'menuitem',
                                handler: function(item, e) {
                                    var workspace = Ext.ComponentQuery.query('container[itemId=workspace]')[0];

                                    var o = Ext.create('ExtJs6ExamplesWorld.view.HtmlEditor');

                                    //
                                    workspace.removeAll();
                                    workspace.add(o);
                                },
                                text: 'Html Editor'
                            },
                            {
                                xtype: 'menuitem',
                                handler: function(item, e) {
                                    var workspace = Ext.ComponentQuery.query('container[itemId=workspace]')[0];

                                    var o = Ext.create('ExtJs6ExamplesWorld.view.Label');

                                    //
                                    workspace.removeAll();
                                    workspace.add(o);
                                },
                                text: 'Label'
                            },
                            {
                                xtype: 'menuitem',
                                handler: function(item, e) {
                                    var workspace = Ext.ComponentQuery.query('container[itemId=workspace]')[0];

                                    var o = Ext.create('ExtJs6ExamplesWorld.view.FieldContainer');

                                    //
                                    workspace.removeAll();
                                    workspace.add(o);
                                },
                                text: 'FieldContainer'
                            },
                            {
                                xtype: 'menuitem',
                                handler: function(item, e) {
                                    var workspace = Ext.ComponentQuery.query('container[itemId=workspace]')[0];

                                    var o = Ext.create('ExtJs6ExamplesWorld.view.FieldSet');

                                    //
                                    workspace.removeAll();
                                    workspace.add(o);
                                },
                                text: 'FieldSet'
                            },
                            {
                                xtype: 'menuitem',
                                handler: function(item, e) {
                                    var workspace = Ext.ComponentQuery.query('container[itemId=workspace]')[0];

                                    var o = Ext.create('ExtJs6ExamplesWorld.view.FormPanel');

                                    //
                                    workspace.removeAll();
                                    workspace.add(o);
                                },
                                text: 'FormPanel'
                            },
                            {
                                xtype: 'menuitem',
                                handler: function(item, e) {
                                    var workspace = Ext.ComponentQuery.query('container[itemId=workspace]')[0];

                                    var o = Ext.create('ExtJs6ExamplesWorld.view.SpinnerField');

                                    //
                                    workspace.removeAll();
                                    workspace.add(o);
                                },
                                text: 'SpinnerField'
                            },
                            {
                                xtype: 'menuitem',
                                handler: function(item, e) {
                                    var workspace = Ext.ComponentQuery.query('container[itemId=workspace]')[0];

                                    var o = Ext.create('ExtJs6ExamplesWorld.view.TagField');

                                    //
                                    workspace.removeAll();
                                    workspace.add(o);
                                },
                                text: 'TagField'
                            },
                            {
                                xtype: 'menuitem',
                                handler: function(item, e) {
                                    var workspace = Ext.ComponentQuery.query('container[itemId=workspace]')[0];

                                    var o = Ext.create('ExtJs6ExamplesWorld.view.TextField');

                                    //
                                    workspace.removeAll();
                                    workspace.add(o);
                                },
                                text: 'TextField'
                            },
                            {
                                xtype: 'menuitem',
                                handler: function(item, e) {
                                    var workspace = Ext.ComponentQuery.query('container[itemId=workspace]')[0];

                                    var o = Ext.create('ExtJs6ExamplesWorld.view.TimeField');

                                    //
                                    workspace.removeAll();
                                    workspace.add(o);
                                },
                                text: 'TimeField'
                            },
                            {
                                xtype: 'menuitem',
                                handler: function(item, e) {
                                    var workspace = Ext.ComponentQuery.query('container[itemId=workspace]')[0];

                                    var o = Ext.create('ExtJs6ExamplesWorld.view.TriggerField');

                                    //
                                    workspace.removeAll();
                                    workspace.add(o);
                                },
                                text: 'TriggerField'
                            },
                            {
                                xtype: 'menuitem',
                                handler: function(item, e) {
                                    var workspace = Ext.ComponentQuery.query('container[itemId=workspace]')[0];

                                    var o = Ext.create('ExtJs6ExamplesWorld.view.ProgressBarWidget');

                                    //
                                    workspace.removeAll();
                                    workspace.add(o);
                                },
                                text: 'ProgressBarWidget'
                            },
                            {
                                xtype: 'menuitem',
                                handler: function(item, e) {
                                    var workspace = Ext.ComponentQuery.query('container[itemId=workspace]')[0];

                                    var o = Ext.create('ExtJs6ExamplesWorld.view.ProgressBar');

                                    //
                                    workspace.removeAll();
                                    workspace.add(o);
                                },
                                text: 'ProgressBar'
                            },
                            {
                                xtype: 'menuitem',
                                handler: function(item, e) {
                                    var workspace = Ext.ComponentQuery.query('container[itemId=workspace]')[0];

                                    var o = Ext.create('ExtJs6ExamplesWorld.view.PagingToolbar');

                                    //
                                    workspace.removeAll();
                                    workspace.add(o);
                                },
                                text: 'PagingToolbar'
                            },
                            {
                                xtype: 'menuitem',
                                handler: function(item, e) {
                                    var workspace = Ext.ComponentQuery.query('container[itemId=workspace]')[0];

                                    var o = Ext.create('ExtJs6ExamplesWorld.view.Toolbar');

                                    //
                                    workspace.removeAll();
                                    workspace.add(o);
                                },
                                text: 'Toolbar'
                            }
                        ]
                    }
                },
                {
                    xtype: 'button',
                    width: 150,
                    text: 'Containers',
                    menu: {
                        xtype: 'menu',
                        width: 120,
                        items: [
                            {
                                xtype: 'menuitem',
                                handler: function(item, e) {
                                    var workspace = Ext.ComponentQuery.query('container[itemId=workspace]')[0];

                                    var o = Ext.create('ExtJs6ExamplesWorld.view.Container');

                                    //
                                    workspace.removeAll();
                                    workspace.add(o);
                                },
                                text: 'Container'
                            },
                            {
                                xtype: 'menuitem',
                                handler: function(item, e) {
                                    var workspace = Ext.ComponentQuery.query('container[itemId=workspace]')[0];

                                    var o = Ext.create('ExtJs6ExamplesWorld.view.Panel');

                                    //
                                    workspace.removeAll();
                                    workspace.add(o);
                                },
                                text: 'Panel'
                            },
                            {
                                xtype: 'menuitem',
                                handler: function(item, e) {
                                    var workspace = Ext.ComponentQuery.query('container[itemId=workspace]')[0];

                                    var o = Ext.create('ExtJs6ExamplesWorld.view.TabPanel');

                                    //
                                    workspace.removeAll();
                                    workspace.add(o);
                                },
                                text: 'TabPanel'
                            },
                            {
                                xtype: 'menuitem',
                                handler: function(item, e) {
                                    var workspace = Ext.ComponentQuery.query('container[itemId=workspace]')[0];

                                    var o = Ext.create('ExtJs6ExamplesWorld.view.Window');

                                    //
                                    workspace.removeAll();
                                    workspace.add(o);
                                },
                                text: 'Window'
                            }
                        ]
                    }
                },
                {
                    xtype: 'button',
                    width: 150,
                    text: 'Messages',
                    menu: {
                        xtype: 'menu',
                        width: 120
                    }
                }
            ]
        },
        {
            xtype: 'container',
            flex: 1,
            id: 'workspace',
            itemId: 'workspace',
            width: 1024,
            layout: 'fit'
        }
    ]

});