/*
 * File: app/view/MyViewport.js
 *
 * This file was generated by Sencha Architect version 4.1.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.2.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.2.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('ExtJs6ExamplesWorld.view.MyViewport', {
    extend: 'Ext.container.Viewport',
    alias: 'widget.myviewport',

    requires: [
        'ExtJs6ExamplesWorld.view.MyViewportViewModel',
        'Ext.tab.Panel',
        'Ext.tab.Tab',
        'Ext.form.FieldSet',
        'Ext.form.Label'
    ],

    viewModel: {
        type: 'myviewport'
    },
    height: 250,
    padding: 10,
    width: 400,
    layout: 'fit',

    items: [
        {
            xtype: 'tabpanel',
            activeTab: 0,
            items: [
                {
                    xtype: 'panel',
                    height: 727,
                    title: 'Main',
                    layout: {
                        type: 'vbox',
                        align: 'stretch',
                        pack: 'center'
                    },
                    items: [
                        {
                            xtype: 'container',
                            flex: 1,
                            layout: {
                                type: 'hbox',
                                align: 'stretch',
                                pack: 'center'
                            },
                            items: [
                                {
                                    xtype: 'fieldset',
                                    flex: 1,
                                    margin: 10,
                                    layout: 'vbox',
                                    title: 'News',
                                    items: [
                                        {
                                            xtype: 'label',
                                            text: '1. 블라블라블라............'
                                        },
                                        {
                                            xtype: 'label',
                                            text: '1. 블라블라블라............'
                                        },
                                        {
                                            xtype: 'label',
                                            text: '1. 블라블라블라............'
                                        },
                                        {
                                            xtype: 'label',
                                            text: '1. 블라블라블라............'
                                        },
                                        {
                                            xtype: 'label',
                                            text: '1. 블라블라블라............'
                                        },
                                        {
                                            xtype: 'label',
                                            text: '1. 블라블라블라............'
                                        },
                                        {
                                            xtype: 'label',
                                            text: '1. 블라블라블라............'
                                        },
                                        {
                                            xtype: 'label',
                                            text: '1. 블라블라블라............'
                                        },
                                        {
                                            xtype: 'label',
                                            text: '1. 블라블라블라............'
                                        },
                                        {
                                            xtype: 'label',
                                            text: '1. 블라블라블라............'
                                        },
                                        {
                                            xtype: 'label',
                                            text: '1. 블라블라블라............'
                                        }
                                    ]
                                },
                                {
                                    xtype: 'fieldset',
                                    flex: 1,
                                    margin: 10,
                                    title: '로드맵'
                                }
                            ]
                        },
                        {
                            xtype: 'container',
                            flex: 1,
                            layout: {
                                type: 'hbox',
                                align: 'stretch',
                                pack: 'center'
                            },
                            items: [
                                {
                                    xtype: 'fieldset',
                                    flex: 1,
                                    margin: 10,
                                    title: 'Google'
                                }
                            ]
                        },
                        {
                            xtype: 'container',
                            flex: 1,
                            layout: {
                                type: 'hbox',
                                align: 'stretch',
                                pack: 'center'
                            },
                            items: [
                                {
                                    xtype: 'fieldset',
                                    flex: 1,
                                    margin: 10,
                                    title: '공지사항'
                                },
                                {
                                    xtype: 'fieldset',
                                    flex: 1,
                                    margin: 10,
                                    title: '기술'
                                }
                            ]
                        }
                    ]
                },
                {
                    xtype: 'panel',
                    height: 727,
                    layout: 'vbox',
                    title: 'Readme'
                },
                {
                    xtype: 'panel',
                    layout: 'fit',
                    title: 'Behaviors',
                    items: [
                        {
                            xtype: 'tabpanel',
                            padding: 10,
                            activeTab: 0,
                            items: [
                                {
                                    xtype: 'panel',
                                    title: 'Tab 1'
                                },
                                {
                                    xtype: 'panel',
                                    title: 'Tab 2'
                                },
                                {
                                    xtype: 'panel',
                                    title: 'Tab 3'
                                }
                            ]
                        }
                    ]
                },
                {
                    xtype: 'panel',
                    layout: 'fit',
                    title: 'Buttons',
                    items: [
                        {
                            xtype: 'tabpanel',
                            padding: 10,
                            activeTab: 0,
                            items: [
                                {
                                    xtype: 'panel',
                                    title: 'Tab 1'
                                },
                                {
                                    xtype: 'panel',
                                    title: 'Tab 2'
                                },
                                {
                                    xtype: 'panel',
                                    title: 'Tab 3'
                                }
                            ]
                        }
                    ]
                },
                {
                    xtype: 'panel',
                    layout: 'fit',
                    title: 'Charts',
                    items: [
                        {
                            xtype: 'tabpanel',
                            padding: 10,
                            activeTab: 0,
                            items: [
                                {
                                    xtype: 'panel',
                                    title: 'Tab 1'
                                },
                                {
                                    xtype: 'panel',
                                    title: 'Tab 2'
                                },
                                {
                                    xtype: 'panel',
                                    title: 'Tab 3'
                                }
                            ]
                        }
                    ]
                },
                {
                    xtype: 'panel',
                    layout: 'fit',
                    title: 'Containers',
                    items: [
                        {
                            xtype: 'tabpanel',
                            padding: 10,
                            activeTab: 0,
                            items: [
                                {
                                    xtype: 'panel',
                                    title: 'Tab 1'
                                },
                                {
                                    xtype: 'panel',
                                    title: 'Tab 2'
                                },
                                {
                                    xtype: 'panel',
                                    title: 'Tab 3'
                                }
                            ]
                        }
                    ]
                },
                {
                    xtype: 'panel',
                    layout: 'fit',
                    title: 'Data',
                    items: [
                        {
                            xtype: 'tabpanel',
                            padding: 10,
                            activeTab: 0,
                            items: [
                                {
                                    xtype: 'panel',
                                    title: 'Tab 1'
                                },
                                {
                                    xtype: 'panel',
                                    title: 'Tab 2'
                                },
                                {
                                    xtype: 'panel',
                                    title: 'Tab 3'
                                }
                            ]
                        }
                    ]
                },
                {
                    xtype: 'panel',
                    layout: 'fit',
                    title: 'Forms',
                    items: [
                        {
                            xtype: 'tabpanel',
                            padding: 10,
                            activeTab: 0,
                            items: [
                                {
                                    xtype: 'panel',
                                    title: 'Tab 1'
                                },
                                {
                                    xtype: 'panel',
                                    title: 'Tab 2'
                                },
                                {
                                    xtype: 'panel',
                                    title: 'Tab 3'
                                }
                            ]
                        }
                    ]
                },
                {
                    xtype: 'panel',
                    layout: 'fit',
                    title: 'Grids',
                    items: [
                        {
                            xtype: 'tabpanel',
                            padding: 10,
                            activeTab: 0,
                            items: [
                                {
                                    xtype: 'panel',
                                    title: 'Tab 1'
                                },
                                {
                                    xtype: 'panel',
                                    title: 'Tab 2'
                                },
                                {
                                    xtype: 'panel',
                                    title: 'Tab 3'
                                }
                            ]
                        }
                    ]
                },
                {
                    xtype: 'panel',
                    layout: 'fit',
                    title: 'Menus',
                    items: [
                        {
                            xtype: 'tabpanel',
                            padding: 10,
                            activeTab: 0,
                            items: [
                                {
                                    xtype: 'panel',
                                    title: 'Tab 1'
                                },
                                {
                                    xtype: 'panel',
                                    title: 'Tab 2'
                                },
                                {
                                    xtype: 'panel',
                                    title: 'Tab 3'
                                }
                            ]
                        }
                    ]
                },
                {
                    xtype: 'panel',
                    layout: 'fit',
                    title: 'Models',
                    items: [
                        {
                            xtype: 'tabpanel',
                            padding: 10,
                            activeTab: 0,
                            items: [
                                {
                                    xtype: 'panel',
                                    title: 'Tab 1'
                                },
                                {
                                    xtype: 'panel',
                                    title: 'Tab 2'
                                },
                                {
                                    xtype: 'panel',
                                    title: 'Tab 3'
                                }
                            ]
                        }
                    ]
                },
                {
                    xtype: 'panel',
                    layout: 'fit',
                    title: 'Premium',
                    items: [
                        {
                            xtype: 'tabpanel',
                            padding: 10,
                            activeTab: 0,
                            items: [
                                {
                                    xtype: 'panel',
                                    title: 'Tab 1'
                                },
                                {
                                    xtype: 'panel',
                                    title: 'Tab 2'
                                },
                                {
                                    xtype: 'panel',
                                    title: 'Tab 3'
                                }
                            ]
                        }
                    ]
                },
                {
                    xtype: 'panel',
                    layout: 'fit',
                    title: 'Resources',
                    items: [
                        {
                            xtype: 'tabpanel',
                            padding: 10,
                            activeTab: 0,
                            items: [
                                {
                                    xtype: 'panel',
                                    title: 'Tab 1'
                                },
                                {
                                    xtype: 'panel',
                                    title: 'Tab 2'
                                },
                                {
                                    xtype: 'panel',
                                    title: 'Tab 3'
                                }
                            ]
                        }
                    ]
                },
                {
                    xtype: 'panel',
                    layout: 'fit',
                    title: 'Themes',
                    items: [
                        {
                            xtype: 'tabpanel',
                            padding: 10,
                            activeTab: 0,
                            items: [
                                {
                                    xtype: 'panel',
                                    title: 'Tab 1'
                                },
                                {
                                    xtype: 'panel',
                                    title: 'Tab 2'
                                },
                                {
                                    xtype: 'panel',
                                    title: 'Tab 3'
                                }
                            ]
                        }
                    ]
                },
                {
                    xtype: 'panel',
                    layout: 'fit',
                    title: 'Trees',
                    items: [
                        {
                            xtype: 'tabpanel',
                            padding: 10,
                            activeTab: 0,
                            items: [
                                {
                                    xtype: 'panel',
                                    title: 'Tab 1'
                                },
                                {
                                    xtype: 'panel',
                                    title: 'Tab 2'
                                },
                                {
                                    xtype: 'panel',
                                    title: 'Tab 3'
                                }
                            ]
                        }
                    ]
                },
                {
                    xtype: 'panel',
                    layout: 'fit',
                    title: 'views',
                    items: [
                        {
                            xtype: 'tabpanel',
                            padding: 10,
                            activeTab: 0,
                            items: [
                                {
                                    xtype: 'panel',
                                    title: 'Tab 1'
                                },
                                {
                                    xtype: 'panel',
                                    title: 'Tab 2'
                                },
                                {
                                    xtype: 'panel',
                                    title: 'Tab 3'
                                }
                            ]
                        }
                    ]
                },
                {
                    xtype: 'panel',
                    layout: 'fit',
                    title: 'About'
                }
            ]
        }
    ]

});