/*
 * File: app/view/NumberField.js
 *
 * This file was generated by Sencha Architect version 4.1.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.2.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.2.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('ExtJs6ExamplesWorld.view.NumberField', {
    extend: 'Ext.container.Container',
    alias: 'widget.NumberField',

    requires: [
        'ExtJs6ExamplesWorld.view.aboutViewModel4',
        'Ext.form.field.Number'
    ],

    viewModel: {
        type: 'numberfield'
    },
    id: 'NumberField',
    itemId: 'NumberField',

    layout: {
        type: 'vbox',
        align: 'center',
        pack: 'center'
    },
    items: [
        {
            xtype: 'numberfield',
            maxWidth: 200,
            fieldLabel: 'Number',
            enforceMaxLength: true,
            growMax: 1,
            maxLength: 2,
            maxValue: 10,
            minValue: 1
        },
        {
            xtype: 'numberfield',
            maxWidth: 200,
            fieldLabel: 'Without spinner',
            enforceMaxLength: true,
            growMax: 1,
            hideTrigger: true,
            maxLength: 2,
            maxValue: 10,
            minValue: 1
        },
        {
            xtype: 'numberfield',
            maxWidth: 200,
            fieldLabel: 'With a step of 0.4',
            enforceMaxLength: true,
            growMax: 1,
            maxLength: 3,
            maxValue: 100,
            minValue: -100,
            step: 0.1
        }
    ]

});