/*
 * File: app/view/Sample.js
 *
 * This file was generated by Sencha Architect version 4.1.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.2.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.2.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('ExtJs6ExamplesWorld.view.Sample', {
    extend: 'Ext.container.Container',
    alias: 'widget.sample',

    requires: [
        'ExtJs6ExamplesWorld.view.aboutViewModel5',
        'Ext.panel.Panel'
    ],

    viewModel: {
        type: 'sample'
    },
    id: 'Sample',
    itemId: 'Sample',
    layout: 'border',

    items: [
        {
            xtype: 'panel',
            region: 'center',
            margin: 5,
            title: 'Components'
        },
        {
            xtype: 'panel',
            floatable: false,
            region: 'east',
            split: true,
            html: '<pre>\nExt.define(\'ExtJs6ExamplesWorld.view.Sample\', {\n    extend: \'Ext.container.Container\',\n    alias: \'widget.sample\',\n\n    requires: [\n        \'ExtJs6ExamplesWorld.view.aboutViewModel5\',\n        \'Ext.panel.Panel\'\n    ],\n\n    viewModel: {\n        type: \'sample\'\n    },\n    id: \'Sample\',\n    itemId: \'Sample\',\n    layout: \'border\',\n\n    items: [\n        {\n            xtype: \'panel\',\n            floatable: false,\n            region: \'east\',\n            split: true,\n            margin: 5,\n            width: 300,\n            collapsible: true,\n            title: \'My Panel\'\n        },\n        {\n            xtype: \'panel\',\n            region: \'center\',\n            margin: 5,\n            title: \'My Panel\'\n        }\n    ]\n\n});\n</pre>',
            margin: 5,
            width: 400,
            collapsible: true,
            title: 'Source'
        }
    ]

});