/*
 * File: app/view/Slider.js
 *
 * This file was generated by Sencha Architect version 4.1.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.2.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.2.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('ExtJs6ExamplesWorld.view.Slider', {
    extend: 'Ext.container.Container',
    alias: 'widget.Slider',

    requires: [
        'ExtJs6ExamplesWorld.view.aboutViewModel10',
        'Ext.slider.Single',
        'Ext.slider.Widget'
    ],

    viewModel: {
        type: 'slider'
    },
    id: 'Slider',
    itemId: 'Slider',

    layout: {
        type: 'vbox',
        align: 'center',
        pack: 'center'
    },
    items: [
        {
            xtype: 'multislider',
            width: 400,
            fieldLabel: 'Label',
            values: [
                10,
                40
            ]
        },
        {
            xtype: 'slider',
            width: 400,
            fieldLabel: 'Label',
            value: 40
        },
        {
            xtype: 'sliderwidget',
            width: 223
        }
    ]

});