/*
 * File: app/controller/controller_toast.js
 *
 * This file was generated by Sencha Architect version 4.1.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.2.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.2.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('ExtJs6ExamplesWorld.controller.controller_toast', {
    extend: 'Ext.app.Controller',
    alias: 'controller.controller_toast',

    control: {
        "#mybutton5": {
            click: 'onMybutton4Click'
        }
    },

    onMybutton4Click: function(button, e, eOpts) {


         Ext.toast({
                    html: 'Simple Toast',
                    closable: false,
                    align: 't',
                    slideDUration: 400,
                    maxWidth: 400
                });


    }

});
